### ISSUE TITLE
A questions about Random forest and ridge regression 

### ISSUE THREAD

**Issue by lixunlove** [cyberport-kaggle/galaxy-zoo#2]
@hxu 
Sorry to bother you again，Finally, I ran out of the results with 24G RAM .Thank you.
I have a question about the Random forest and ridge regression ，Ridge regression can  get the results why use a random forest after that? 
thank you

**Comment by hxu** [comment]
If I recall correctly, this was because the random forest can account for nonlinear and interaction effects between the various predicted values, whereas ridge regression is just linear regression.  I think that in some cases it provides a small boost to the accurate, though the impact is not large.

**Comment by lixunlove** [comment]
Ok  Thank  you，I will  verify the results by experiment.
